[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

# Optimization Configs
optimizer_runs = 200
via_ir = false

# RPC endpoints for different networks
[rpc_endpoints]
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/IKuWUIfOxsfG2DFNZOmnt"
base = "https://base-mainnet.g.alchemy.com/v2/IKuWUIfOxsfG2DFNZOmnt"

# Contracts check configuration
[profile.base_sepolia]
optimizer_runs = 800
via_ir = true
# Gas settings for the testnet
gas_limit = 30000000
gas_price = 1000000000  # 1 gwei
priority_gas_price = 1000000000

# Production configs
[profile.base]
optimizer_runs = 1000
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
